import { useState } from "react";
import { Dialog, Field, Select } from "./components";
import { Thumbnail } from "./Canvas";
import { api } from "./api";
import { parsePages, type Session } from "../../../packages/editor-state/types";
export function InsertPdf({source,current,total,onClose,onInsert}:{source:Session;current:number;total:number;onClose:()=>void;onInsert:(data:string,at:number)=>Promise<void>}){
  const [selected,setSelected]=useState(source.info.pages.map((_,i)=>i)),[range,setRange]=useState("all"),[position,setPosition]=useState("After current page"),[busy,setBusy]=useState(false),[error,setError]=useState("");
  return <Dialog title="Insert PDF" onClose={onClose} wide><div className="insert-pdf"><div className="insert-summary"><strong>{source.name}</strong><span>{source.info.pages.length} pages</span></div><div className="insert-pages">{source.info.pages.map((_,i)=><button key={i} aria-label={`Select imported page ${i+1}`} aria-pressed={selected.includes(i)} className={selected.includes(i)?"selected":""} onClick={()=>{const next=selected.includes(i)?selected.filter(n=>n!==i):[...selected,i].sort((a,b)=>a-b);setSelected(next);setRange(next.map(v=>v+1).join(", "));}}><Thumbnail doc={source} page={i}/><span>{i+1}</span><i>{selected.includes(i)?"✓":""}</i></button>)}</div><div className="insert-config"><Field label="Pages"><input value={range} onChange={e=>{setRange(e.target.value);try{setSelected(parsePages(e.target.value,source.info.pages.length));setError("");}catch{setError("Enter a page range, such as 1, 3–5, or all.");}}}/></Field><Field label="Insert"><Select label="Insertion position" value={position} onChange={setPosition} options={["Before current page","After current page","Beginning","End"]}/></Field><span>{selected.length} pages selected</span></div>{error&&<p className="new-document-error">{error}</p>}<footer><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy||!selected.length||!!error} onClick={async()=>{setBusy(true);try{const data=await api<string>("extract",source.id,{pages:selected});await onInsert(data,position==="Beginning"?0:position==="End"?total:current+(position==="After current page"?1:0));onClose();}catch(e){setError(String(e));}finally{setBusy(false);}}}>{busy?"Inserting…":"Insert pages"}</button></footer></div></Dialog>;
}
