import {task, navigation, command as workbenchCommand} from "./workbench-helpers";
import {test,expect,type Page} from '@playwright/test';
import path from 'node:path';
import fs from 'node:fs/promises';
const folder='tmp/qa/papier';
test.use({actionTimeout:15000});
async function ready(page:Page){await expect(page.locator('.statusbar .spin')).toHaveCount(0);await expect.poll(()=>page.locator('.pdf-page').first().evaluate(el=>el.getAttribute('data-render-required')===el.getAttribute('data-rendered'))).toBe(true);}
async function shot(page:Page,name:string){await page.screenshot({path:`${folder}/${name}.png`,animations:'disabled'});}
async function command(page:Page,name:string){await page.keyboard.press('Control+k');await page.getByRole('combobox',{name:'Search tools'}).fill(name);await page.getByRole('option',{name:new RegExp(name,'i')}).first().click();}
async function openFixture(page:Page){const choose=page.waitForEvent('filechooser');await page.getByRole('button',{name:/Open PDF…/}).click();await(await choose).setFiles(path.resolve('tests/fixtures/studio-brief.pdf'));await expect(page.locator('.pdf-object').filter({hasText:'A considered'})).toBeVisible();await ready(page);}

test('Papier home, editable presets, signature vectors and persistent recents',async({page})=>{
  test.setTimeout(120000);await fs.mkdir(folder,{recursive:true});await page.goto('/');
  await expect(page.getByRole('heading',{name:'Papier',exact:true})).toBeVisible();await expect(page.locator('.rail')).toHaveCount(0);await expect(page.locator('.inspector')).toHaveCount(0);await shot(page,'01-home');
  await page.getByRole('button',{name:/New document/}).click();await shot(page,'02-new-document');await page.getByRole('button',{name:'Create',exact:true}).click();await ready(page);await shot(page,'03-blank');
  await page.keyboard.press('Control+n');await page.getByRole('button',{name:'Academic',exact:true}).click();await page.getByRole('button',{name:/ABNT Academic/}).click();await page.getByRole('button',{name:'Create',exact:true}).click();await expect(page.locator('#page-0 .pdf-object').filter({hasText:'NOME DA INSTITUIÇÃO'})).toBeVisible();await ready(page);await shot(page,'04-abnt');
  await task(page,"Sign");await page.getByPlaceholder('Enter your name').fill('José Alex Xavier');await shot(page,'11-signature-studio');await page.getByRole('button',{name:'Rubric',exact:true}).click();await shot(page,'12-rubric');await page.getByRole('button',{name:'Customize',exact:true}).click();await page.getByRole('button',{name:'Save to library',exact:true}).click();await expect(page.locator('.signature-candidates button')).toHaveCount(1);await page.getByRole('button',{name:'Place signature'}).click();await expect(page.locator('.object-selection')).toBeVisible();await ready(page);
  await page.keyboard.press('Control+Shift+s');await shot(page,'17-save-as');const save=page.waitForEvent('download');await page.getByRole('dialog').getByRole('button',{name:'Save',exact:true}).click();await(await save).saveAs(`${folder}/academic-signed.pdf`);
  const sessions=await page.evaluate(async()=>{const r=await fetch('/__engine',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'sessions'})});return(await r.json()).value;});const original=sessions.find((s:any)=>s.name==='ABNT Academic.pdf');
  expect(original.info.pages).toHaveLength(7);
  const exported=await fs.readFile(`${folder}/academic-signed.pdf`);const reopened=await page.request.post('/__engine',{data:{action:'import',payload:{name:'academic-reopened.pdf',data:exported.toString('base64')}}});const parsed=(await reopened.json()).value;
  const inspected=await page.request.post('/__engine',{data:{action:'inspect',id:parsed.id,payload:{page:0}}});expect((await inspected.json()).value.some((o:any)=>o.kind==='path')).toBe(true);
  await page.getByRole('button',{name:'Home',exact:true}).click();await expect(page.locator('.quiet-file')).not.toHaveCount(0);await shot(page,'01-home');await page.reload();await expect(page.locator('.quiet-file').filter({hasText:'academic-reopened.pdf'}).first()).toBeVisible();
});

test('direct object manipulation persists; menus, PDF insertion and comparison render',async({page})=>{
  test.setTimeout(150000);await page.goto('/');await openFixture(page);await shot(page,'05-editor');
  const object=page.locator('.pdf-object').filter({hasText:'A considered'});await object.click();await shot(page,'06-text');
  const before=await object.boundingBox();await page.mouse.move(before!.x+10,before!.y+10);await page.mouse.down();await page.mouse.move(before!.x+47,before!.y+33,{steps:8});await page.mouse.up();
  await expect.poll(async()=>Math.round((await object.boundingBox())!.x)).toBeGreaterThan(Math.round(before!.x+20));await ready(page);
  await object.dblclick();await page.getByRole('textbox',{name:'Edit text on page'}).fill('Papier document');await page.getByRole('textbox',{name:'Edit text on page'}).press('Enter');await expect.poll(async()=>await page.getByRole('heading',{name:'Choose a replacement font'}).isVisible() || await page.locator('.pdf-object').filter({hasText:'Papier document'}).isVisible()).toBe(true);if(await page.getByRole('heading',{name:'Choose a replacement font'}).isVisible())await page.getByRole('button',{name:'Apply text',exact:true}).click();await expect(page.locator('.pdf-object').filter({hasText:'Papier document'})).toBeVisible();
  await page.locator('.pdf-object').filter({hasText:'Papier document'}).click({button:'right'});await shot(page,'15-context-menu');await page.keyboard.press('Escape');
  const chooser=page.waitForEvent('filechooser');await workbenchCommand(page,'Insert image');await(await chooser).setFiles(path.resolve('tests/fixtures/landscape.png'));await expect(page.locator('#page-0 .pdf-object[title="image"]')).toHaveCount(2);await ready(page);const image=page.locator('.pdf-object[title="image"]').last();await image.click();await shot(page,'07-image');const size=await image.boundingBox();const handle=await page.getByRole('button',{name:'Resize se',exact:true}).boundingBox();await page.mouse.move(handle!.x+3,handle!.y+3);await page.mouse.down();await page.mouse.move(handle!.x+55,handle!.y+25,{steps:8});await page.mouse.up();await expect.poll(async()=>Math.round((await image.boundingBox())!.width)).toBeGreaterThan(Math.round(size!.width+25));
  await task(page,'Annotate');await workbenchCommand(page,'Draw');await shot(page,'08-brush');const bounds=await page.locator('#page-0 .pdf-page').boundingBox();await page.mouse.move(bounds!.x+210,bounds!.y+430);await page.mouse.down();await page.mouse.move(bounds!.x+250,bounds!.y+400,{steps:6});await page.mouse.move(bounds!.x+310,bounds!.y+430,{steps:6});await page.mouse.up();await ready(page);
  await task(page,"Pages");await shot(page,'09-pages');
  const insert=page.waitForEvent('filechooser');await command(page,'Insert PDF');await(await insert).setFiles(path.resolve('tests/fixtures/studio-brief.pdf'));await expect(page.getByRole('dialog')).toBeVisible();await shot(page,'10-add-pdf');await page.getByRole('combobox',{name:'Insertion position'}).click();await page.getByRole('option',{name:'Beginning',exact:true}).click();await page.getByRole('button',{name:'Insert pages',exact:true}).click();await expect(page.getByRole('button',{name:'Select page 6',exact:true})).toBeVisible();
  await task(page,"Forms");await shot(page,'13-forms');await page.keyboard.press('Control+k');await page.getByRole('combobox',{name:'Search tools'}).fill('comp');await shot(page,'14-command-palette');await page.keyboard.press('Escape');
  const compare=page.waitForEvent('filechooser');await command(page,'Compare PDFs');await(await compare).setFiles(path.resolve('tests/fixtures/studio-brief.pdf'));await expect(page.locator('.comparison-page img').first()).toBeVisible();await shot(page,'16-compare');await page.getByRole('button',{name:'Close dialog',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button',{name:'Settings'}).click();await shot(page,'18-settings');await page.getByRole('button',{name:'Close dialog',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
  const save=page.waitForEvent('download');await page.keyboard.press('Control+s');await(await save).saveAs(`${folder}/manipulated.pdf`);
  const data=await fs.readFile(`${folder}/manipulated.pdf`);const reopened=await page.request.post('/__engine',{data:{action:'import',payload:{name:'manipulated-reopened.pdf',data:data.toString('base64')}}});const state=(await reopened.json()).value;expect(state.info.pages).toHaveLength(6);const text=await page.request.post('/__engine',{data:{action:'text',id:state.id}});expect((await text.json()).value.join(' ')).toContain('Papier document');
});
